In [1]:
import numpy as np

In [29]:
a1=np.arange(12) 
a2=np.arange(16).reshape(4,4)
a3=np.arange(8).reshape(2,4)

In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
a2[(a2%2==0) & (a2%3==0)]


array([ 0,  6, 12])

In [32]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [33]:
a4=np.arange(8).reshape(2,2,2)
for i in a4:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [34]:
#Converting 3d,2d into 1d
np.ravel(a4)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.nditer(a4)
