In [1]:
import numpy as np

In [2]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a3=np.arange(8).reshape(2,4)

In [4]:
a2[0]

array([12, 13, 14, 15])

In [5]:
a2[0][1]

np.int64(13)

In [6]:
a2[0,1]

np.int64(13)

In [9]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2[1][2:4]

array([18, 19])

#### In NumPy, slicing means extracting a portion of an array by specifying a range of indices along one or more dimensions, without creating a copy (by default) — it returns a view of the original array.

In [12]:
a2[1:2,2:4]

array([[18, 19]])

In [23]:
a2[0:3,-1]

array([15, 19, 23])

In [17]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a2[[1,1,2,2,2],[0,2,0,1,2]] #Fancy indexing

array([16, 18, 20, 21, 22])

In [33]:
#3D array
a4=np.arange(8).reshape(2,2,2)
#First number will tell how many blocks are there
#Rest two numbers will tell the size
a4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a4[1,1,1]

np.int64(7)

In [36]:
a4[0:2,0:1,0:1]

array([[[0]],

       [[4]]])