In [2]:
import numpy as np

In [5]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a3=np.arange(8).reshape(2,4)

In [23]:
a1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
np.max(a1)


np.int64(11)

In [21]:
np.min(a2)

np.int64(12)

In [10]:
np.max(a2,axis=1)#rows wise max

array([15, 19, 23])

In [11]:
np.min(a1,axis=0)#Column Wise 

array([0, 1, 2, 3])

In [12]:
np.sum(a3,axis=1)

array([ 6, 22])

In [13]:
np.prod(a2)

np.int64(647647525324800)

In [14]:
np.mean(a2)#Average

np.float64(17.5)

In [15]:
np.median(a3)

np.float64(3.5)

In [16]:
np.std(a1)

np.float64(3.452052529534663)

In [17]:
np.var(a3)

np.float64(5.25)

In [18]:
np.log(a2)

array([[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422]])

In [19]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [20]:
np.cos(a2)

array([[ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302]])

In [7]:
np.sin(a3)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [8]:
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [28]:
np.round(np.tan(a2))

array([[-1.,  0.,  7., -1.],
       [ 0.,  3., -1.,  0.],
       [ 2., -2.,  0.,  2.]])

In [27]:
np.max(np.ceil(np.tan(a2))) #method chaining

np.float64(8.0)

In [30]:
np.ceil(np.tan(a2)).astype(int)

array([[ 0,  1,  8,  0],
       [ 1,  4, -1,  1],
       [ 3, -1,  1,  2]])