In [1]:
import numpy as np

In [2]:
a1=np.arange(12).reshape(3,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [5]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [6]:
a3=np.arange(8).reshape(2,4)

In [ ]:
a3*a2 #shape must be same

ValueError: operands could not be broadcast together with shapes (2,4) (3,4) 

In [17]:
a3+a1 #could not be broadcast together with shapes (2,4) (3,4) 

ValueError: operands could not be broadcast together with shapes (2,4) (3,4) 